### PR TITLE
feat + fix: change user balance reset logic

### PR DESCRIPTION
**Pull request by edcous**
feat: adds transaction when user balance is reset
fix: changes logic to ensure that balance expiration is not reset before balance is

### CODE REVIEW

**Review by mswider — APPROVED** [review]
Looks good to me!

**Comment by mswider** [comment]
## Todo:
 - [x] Prevent teachers from reversing system transactions (this takes their money away)
 - [x] Exclude system from reports queries
 - [x] Updated balance is not saved to DB
   - This leads to new transactions for every time the balance is loaded
   - It also means that the staff page (uses `/api/balance/me`) doesn't update the balance

**Review by mswider — CHANGES_REQUESTED** [review]
Address issues

**Review by mswider — APPROVED** [review]

**Comment by mswider** [comment]
@edcous anything look off or do you think this looks done?

**Comment by edcous** [comment]
Looks good to me!

**Pull request merged**
